services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/angeelmdev/angeltech.es/web:latest
    ports:
      - "8050:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - network_angeltech

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    networks:
      - network_angeltech

networks:
  network_angeltech:

volumes:
  data:
  