services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/angeelmdev/angeltech.es/web:latest
    ports:
      - "8050:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    depends_on:
      - db
    networks:
      - network_angeltech

  node:
    image: node:20
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./node_modules:/var/www/html/node_modules
    command: npm run watch
    networks:
      - network_angeltech
    depends_on:
      - php

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    networks:
      - network_angeltech

networks:
  network_angeltech:

volumes:
  data:
